name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload binaries to release
      uses: kittaakos/upload-release-action@dev
      with:
        repo_token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
        repo_name: kittaakos/upload-release-action--target
        release_name: ${{ github.event.release.tag_name }}
        file: assets/*
        tag: ${{ github.ref }}
        file_glob: true
        body: "release body content"