name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Tag
      id: tag_name
      run: |
        echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

    - name: Upload binaries to release
      uses: kittaakos/upload-release-action@dev
      with:
        repo_token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
        repo_name: kittaakos/upload-release-action--target
        release_name: ${{ steps.tag_name.outputs.TAG_NAME }}
        file: assets/*
        tag: ${{ github.ref }}
        file_glob: true
        body: "release body content"